foo: foo version 2
#democonfigclient.message=hello spring io
message: this is message
# INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
#eureka信息配置
eureka:
  client:
    serviceUrl:
#      defaultZone: http://chendom:root123@localhost:8500/eureka/
      defaultZone: http://localhost:15000/eureka/
  instance:
     prefer-ip-address: true
#     #定制应用的名称
     instance-id: ${spring.application.name}:${server.port}
