#security:
#  basic:
#    enabled: true
#  user:
#    name: chendom  # 用户名
#    password: root123   # 用户密码
server:
  port: 15000
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#     defaultZone: http://chendom:root123@localhost:8500/eureka/
     defaultZone: http://localhost:15000/eureka/
endpoints:
  shutdown:
    enabled: true #传统地址